In [2]:
import pandas as pd
import numpy as np
from scipy.stats import mode

In [28]:
df1 = pd.read_csv('total.csv')

In [29]:
df1.drop('Unnamed: 0', axis=1, inplace=True)

In [30]:
df1.head(20)

,user,comment,user_orig,comment_orig
0,_reLight_,INTJ and ISFJ. If you know what I mean. ( êÁå¡...,b'_reLight_',b'INTJ and ISFJ. If you know what I mean. ( \x...
1,142o,It is not uncommon to find INTP men who claim ...,b'142o',"b""It is not uncommon to find INTP men who clai..."
2,142o,Many if not most people with INTP's have no pr...,b'142o',b'Many if not most people with INTP\'s have no...
3,46makun,ENTP guilty of the same kind of behavior as yo...,b'46makun',b'ENTP guilty of the same kind of behavior as ...
4,46makun,"I would say for ENTPs it should be ""Being forc...",b'46makun',"b'I would say for ENTPs it should be ""Being fo..."
5,4ArthurDent2,For the record r/INTP is way worse. \r\rBut I...,b'4ArthurDent2',b'For the record r/INTP is way worse. \n\nBut...
6,Acedrew89,"""it hasn't been proven to me yet that somethin...",b'Acedrew89',"b'""it hasn\'t been proven to me yet that somet..."
7,acontreras1228,I'm also an INTP who finds myself in this same...,b'acontreras1228',"b""I'm also an INTP who finds myself in this sa..."
8,alaniko,&gt; INTP\r\r&gt; While aware of the emotions ...,b'alaniko',"b""&gt; INTP\n\n&gt; While aware of the emotion..."
9,AlarmingInteger,I think I see what you're getting at. What I'm...,b'AlarmingInteger',b'I think I see what you\'re getting at. What ...
10,AlarmingInteger,"It's interesting that you read it that way, fo...",b'AlarmingInteger',"b'It\'s interesting that you read it that way,..."
11,AlmightyBox,&gt; perhaps that field is better suited for i...,b'AlmightyBox',b'&gt; perhaps that field is better suited for...
12,alphalady,Just a joke but came across a post one day tha...,b'alphalady',"b""Just a joke but came across a post one day t..."
13,alphalady,I commented somewhere a long time ago explaini...,b'alphalady',b'I commented somewhere a long time ago explai...
14,alphalady,Yeah I was surprised to see few people saying ...,b'alphalady',"b""Yeah I was surprised to see few people sayin..."
15,alphalady,I see Andy as ESFP. He's an entertainer and he...,b'alphalady',"b""I see Andy as ESFP. He's an entertainer and ..."
16,alphalady,"Well, as someone who's totally been in your po...",b'alphalady',"b""Well, as someone who's totally been in your ..."
17,alphalady,LOL what noooo. Ugh i don't know how to put it...,b'alphalady',"b""LOL what noooo. Ugh i don't know how to put ..."
18,alphalady,"Lmfao. First of all, most ENTPs don't have soc...",b'alphalady',"b""Lmfao. First of all, most ENTPs don't have s..."
19,alphalady,I know i know. I'm questioning everything I kn...,b'alphalady',"b""I know i know. I'm questioning everything I ..."

In [31]:
personality = ['ENFJ','ENFP','ESFP', 'ESFJ', 'INFJ','INFP','ISFP','ISFJ','INTJ','INTP','ISTP','ISTJ','ENTJ','ENTP','ESTP','ESTJ']

In [32]:
df1['personality_label'] = pd.Series('0', index=df1.index)

In [51]:
pattern = '|'.join(personality)

In [57]:
df2 = df1[(df1['comment'].str.contains(pattern)) & (df1['comment'].str.contains('I am') | df1['comment'].str.contains('I\'m') | df1['comment'].str.contains('i\'m') | df1['comment'].str.contains('i\'m'))]
#df2 = df1[(df1['comment'].str.contains('INTJ')) & (df1['comment'].str.contains('I am') | df1['comment'].str.contains('I\'m') | df1['comment'].str.contains('i\'m') | df1['comment'].str.contains('i\'m'))]

In [58]:
for index, row in df2.iterrows():
    value = df1.get_value(index, 'comment')
    if type(value) != str:
            continue
    for type_p in personality:
        if (type_p in value) and (('I am an' in value) or ('I\'m an') in value or ('i am an') in value or ('i\'m an') in value):
            df2.set_value(index, 'personality_label', type_p)

In [61]:
df2.head(10)

,user,comment,user_orig,comment_orig,personality_label
7,acontreras1228,I'm also an INTP who finds myself in this same...,b'acontreras1228',"b""I'm also an INTP who finds myself in this sa...",0
9,AlarmingInteger,I think I see what you're getting at. What I'm...,b'AlarmingInteger',b'I think I see what you\'re getting at. What ...,0
10,AlarmingInteger,"It's interesting that you read it that way, fo...",b'AlarmingInteger',"b'It\'s interesting that you read it that way,...",0
11,AlmightyBox,&gt; perhaps that field is better suited for i...,b'AlmightyBox',b'&gt; perhaps that field is better suited for...,INTP
12,alphalady,Just a joke but came across a post one day tha...,b'alphalady',"b""Just a joke but came across a post one day t...",0
13,alphalady,I commented somewhere a long time ago explaini...,b'alphalady',b'I commented somewhere a long time ago explai...,0
15,alphalady,I see Andy as ESFP. He's an entertainer and he...,b'alphalady',"b""I see Andy as ESFP. He's an entertainer and ...",0
17,alphalady,LOL what noooo. Ugh i don't know how to put it...,b'alphalady',"b""LOL what noooo. Ugh i don't know how to put ...",0
19,alphalady,I know i know. I'm questioning everything I kn...,b'alphalady',"b""I know i know. I'm questioning everything I ...",0
24,aSaDISTICMOTHERFUCKr,Honestly I'm impressed. The first ISTJ friend ...,b'aSaDISTICMOTHERFUCKr',"b""Honestly I'm impressed. The first ISTJ frien...",0

In [62]:
df2 = df2.groupby(['user','personality_label']).count().reset_index()

In [63]:
df2.head(30)

                    user personality_label  comment  user_orig  comment_orig
0                 #NAME?                 0       99         99            99
1                 #NAME?              ENTJ        7          7             7
2                 #NAME?              ENTP        3          3             3
3                 #NAME?              ESTJ        3          3             3
4                 #NAME?              INFP        5          5             5
5                 #NAME?              INTJ        4          4             4
6                 #NAME?              INTP        4          4             4
7                 #NAME?              ISTJ        4          4             4
8              --TyDog--                 0        1          1             1
9   --wubbalubbadubdub--                 0        1          1             1
10               -1mar7-              ISTP        1          1             1
11          -Afrodisiac-                 0       18         18            18
12          -Afrodisiac-              ENTP        2          2             2
13          -Anna_Molly-                 0        1          1             1
14        -Avatar-Korra-                 0        1          1             1
15        -Avatar-Korra-              INTP        1          1             1
16         -B1ackRibbon-              ENTP        2          2             2
17              -Joefus-                 0        1          1             1
18        -Joey-Wheeler-                 0        1          1             1
19       -JonathanDrake-                 0        1          1             1
20             -JungleB-                 0        1          1             1
21             -JungleB-              INFP        1          1             1
22             -Kaionic-                 0       32         32            32
23             -Kaionic-              ISTJ        2          2             2
24        -MelodyDragon-              INFP        1          1             1
25        -Quintessence-                 0        1          1             1
26         -RedStateRed-                 0        1          1             1
27            -Riukkuyo-                 0        2          2             2
28               -SagaQ-                 0       18         18            18
29        -SeraWasNever-                 0        1          1             1

In [64]:
df3 = df2[df2.personality_label != '0']

In [65]:
df3.head()

     user personality_label  comment  user_orig  comment_orig
1  #NAME?              ENTJ        7          7             7
2  #NAME?              ENTP        3          3             3
3  #NAME?              ESTJ        3          3             3
4  #NAME?              INFP        5          5             5
5  #NAME?              INTJ        4          4             4

In [74]:
df2.to_csv('reduced_labels.csv')